### ISSUE TITLE
Cann't Run example

### ISSUE THREAD

**Issue by toby20130333** [KDAB/DeclarativeWidgets#23] opened 2018-12-06 08:30 UTC
Hi All:

I got this source code
and build it OK
and install it OK
but not run those examples failed

get the errors is:
for examle: bookstore
QML debugging is enabled. Only use this in a safe environment.
authorTable.rowCount= 4
QQmlComponent: Component is not ready
Failed to create widget from QML

**Comment by 0x6e** [comment] 2018-12-10 12:51
Hello,
thanks for letting us know. I could reproduce this issue here, so I'll get some time scheduled to look into it.

Kind regards,
Nathan

**Comment by CrawlWu** [comment] 2020-03-31 09:13
@toby20130333 Hello, have you got it? I am facing the same problem as you.

**Comment by shujaatak** [comment] 2020-04-02 10:07
I am facing the same issue too!

**Comment by toby20130333** [comment] 2020-04-08 08:46
@CrawlWu @shujaatak  I cann't solve it

**Comment by 0x6e** [comment] 2020-04-09 16:07
Could you please provide compiler and Qt version details?

If you are getting the `QQmlComponent: Component is not ready` message this indicates that the QtWidgets QML plugin has not been installed correctly. Please make sure you have built and installed the release version of the plugin.

**Comment by shujaatak** [comment] 2020-04-09 18:44
> Could you please provide compiler and Qt version details?
> 
> If you are getting the `QQmlComponent: Component is not ready` message this indicates that the QtWidgets QML plugin has not been installed correctly. Please make sure you have built and installed the release version of the plugin.

I am using Qt5.14.1_msvc2017_64bit, but I have noticed it did not worked with other Qt versions too. I have that noticed that Admin.qml and Staff.qml run fine but when I selected Developer.qml then the application crashes.

**Comment by shujaatak** [comment] 2020-04-09 18:47
> Could you please provide compiler and Qt version details?
> 
> If you are getting the `QQmlComponent: Component is not ready` message this indicates that the QtWidgets QML plugin has not been installed correctly. Please make sure you have built and installed the release version of the plugin.

I don't know what do you mean by "QtWidgets QML plugin has not been installed correctly" as I routinely make Qt Quick applications in Qt so QML plugin should not be the cause of this issue.

**Comment by shujaatak** [comment] 2020-04-09 18:54
> Could you please provide compiler and Qt version details?
> 
> If you are getting the `QQmlComponent: Component is not ready` message this indicates that the QtWidgets QML plugin has not been installed correctly. Please make sure you have built and installed the release version of the plugin.

When I remove the following code from DeclarativeWidgets->examples->bookstore->widgets->Developer.qml, then the bookstore application runs fine:
```
    Dialog {
        id: shopWindow
        windowTitle: qsTr("Shop")

        VBoxLayout {
            QuickWidget {
                source: "qrc:///qtquick/Shop.qml"

                rootContext: QmlContext {
                    QmlContextProperty {
                        name: "_store"
                        value: _store
                    }
                }
            }
        }
    }
```

**Comment by shujaatak** [comment] 2020-04-09 19:06
@0x6e This is the the Application Output:
```
Starting C:\Qt_Sandbox\Declarative_Widgets\build-declarativewidgets-Desktop_Qt_5_14_1_MSVC2017_64bit-Release\examples\bookstore\release\bookstore.exe ...
authorTable.rowCount= 4
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
QQmlComponent: Component is not ready
Failed to create widget from QML
00:02:39: The program has unexpectedly finished.
00:02:39: The process was ended forcefully.
00:02:39: C:\Qt_Sandbox\Declarative_Widgets\build-declarativewidgets-Desktop_Qt_5_14_1_MSVC2017_64bit-Release\examples\bookstore\release\bookstore.exe crashed.
```

**Comment by shujaatak** [comment] 2020-04-09 19:19
@0x6e If I select any of the following modes then the bookstore example runs fine: _**admin|staff|shop**_ **but** if I run the bookstore example **without** specifying the mode then the application crashes at the startup. From bookstore's main.c it seems that the developer.qml file is meant to be loaded when no mode is specified.

**Comment by shujaatak** [comment] 2020-04-09 19:24
@0x6e I am here to happily test/tell/report anything needed to resolve this issue.  Hope to hear from you and other KDAB's guys working on DeclarativeWidgets soon.

**Comment by shujaatak** [comment] 2020-04-09 19:38
@0x6e I noticed that simply commenting the following lines from the Dialog with id: shopWindow in Developer.qml stops the bookstore example from crashing:

```
//                    rootContext: QmlContext {
//                        QmlContextProperty {
//                            name: "_store"
//                            value: _store
//                        }
//                    }
```
It may give you some more hints to resolve the issue.

**Comment by krake-kdab** [comment] 2020-04-09 19:58
This might be related to the change Qt has made to QQmlContext::setContextProperty()

Shouldn't crash of course, as the function has only been deprecated, but who knows if they did more than just that

**Comment by shujaatak** [comment] 2020-04-10 06:10
Resolving this  issue is utmost necessary as I have noticed that this is the default example which gets run when the developer build and run the DeclarativeWidgets project, so any crash etc gives the bad first impression!
Yeah, from the bookstore example, one can remove those lines which cause issues but note that running away from the bugs instead of resolving those bugs is not the solution. also it would not make DeclarativeWidgets any better.

**Closed** 2020-04-30 10:47 UTC
